services:

  mysql:
    image: mysql:8
    container_name: stock-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stock_portfolio

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: stock-backend

    depends_on:
      - mysql

    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      TWELVEDATA_API_KEY: ${TWELVEDATA_API_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      RESEARCH_UPLOAD_DIR: ${RESEARCH_UPLOAD_DIR}

    ports:
      - "8080:8080"

    volumes:
      - research_uploads:/app/uploads/research

  frontend:
    build: ./frontend
    container_name: stock-frontend

    depends_on:
      - backend

    ports:
      - "5173:5173"

volumes:
  mysql_data:
  research_uploads: