services:

  mysql:
    image: mysql:8
    container_name: stock-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stock_portfolio

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: stock-backend

    depends_on:
      - mysql

    environment:
      DB_PASSWORD: root
      JWT_SECRET: your_jwt_secret
      TWELVEDATA_API_KEY: your_api_key
      GOOGLE_CLIENT_ID: your_google_client_id
      GOOGLE_CLIENT_SECRET: your_google_client_secret
      RESEARCH_UPLOAD_DIR: /app/uploads/research

    ports:
      - "8080:8080"

    volumes:
      - research_uploads:/app/uploads/research

  frontend:
    build: ./frontend
    container_name: stock-frontend

    depends_on:
      - backend

    ports:
      - "5173:5173"

volumes:
  mysql_data:
  research_uploads: